FROM php:8.2-fpm

# Update package lists and install the MySQL client development library
RUN apt-get update && apt-get install -y default-libmysqlclient-dev

# Install the pdo_mysql extension
RUN docker-php-ext-install pdo_mysql

CMD ["php", "-m"]
