version: "3.8"

services:
  laravel-php:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    container_name: laravel-php
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=laravel-mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laraveluser
      - DB_PASSWORD=secret
    depends_on:
      - laravel-mysql

  laravel-nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - laravel-php

  laravel-mysql:
    image: mysql:8
    container_name: laravel-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql

  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile.flask
    container_name: flask-api
    ports:
      - "5000:5000"
    volumes:
      - ./ml:/app

volumes:
  db-data:
